### ISSUE TITLE
Load files from subdirectories

### ISSUE THREAD

**Issue by matcho** [ar4mirez/hapi-octopus#3]
Hello,

I like this plugin !

Just a suggestion here : could be interesting if routes / methods / … were loaded from sub-directories too, for the sake of organization.

Maybe someting like :
 * routes
   * cats
     * cats_get_by_id.js
     * cats_get_by_nickname.js
     * …
   * squirrels
     * squirrels_get_by_location.js
     * squirrels_get_by_fur_color.js
     * …
 * methods
   * cats
     * …
   * squirrels
     * …
 * …

What do you think ?

All the best,
Mathias

**Comment by ar4mirez** [comment]
Hi @matcho thanks for your comments 👍 I appreciate that you like the plugin. The functionality you asking for is already available my mistake I didn't have the README up to date, you can do something like:

```javascript
{
  methods: {
    cwd: `${process.cwd()}/methods`,
    pattern: '**/*.js'
  },
  routes: {
    cwd: `${process.cwd()}/routes`,
    pattern: '**/*.js'
  }
  ...
}
```

I do apologies for the delay response, I hope this helps.

**Comment by matcho** [comment]
Hi @ar4mirez 

Thanks a lot for your answer ! I'll try this today.

Glad to see this plugin is even better than I expected :)

All the best,
Mathias

**Comment by ar4mirez** [comment]
awesome please let me know how it goes or if anything else I can help with.

**Comment by matcho** [comment]
Works like a charm, thanks again !

**Comment by ar4mirez** [comment]
awesome, happy coding! I'll update the README later then.
